<?php

namespace DietpackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdditionalInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalInfoRepository extends EntityRepository
{
}
