<?php

namespace DietpackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DietRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DietRepository extends EntityRepository
{
}
